### ISSUE TITLE
Style feedback (dev.wavefarm.org)

### ISSUE THREAD

**Issue by gsf** [wavefarm/site#29]
From Antony:
- [x] Let's lose the Open Sans and Oswald and replace with Montserrat. 
- [x] Wave farm logo is bigger than mine (mine is 220px wide)
- [x] Slideshow image is bigger than mine (mine is 760px wide)
- [x] "search" should be montserrat, very compressed
- [x] TA and WGXC icons move a little on rollover. Can we get them not to?
- [x] Footer text (the non-nav items) should be about 40% the size of the nav links: I have them specced at 24 (nav links), 10 (LEGAL / PRIVACY) and 11 (studio addresses, which should link to the appropriate contact page). 
- [x] Footer Nav links should be #b3b2b2; over and down states of these links should be #525151 (sorry, I didn't really address that in the PSDs)
- [x] © wave farm should be #858585
- [x] Studio addresses should be #999; these should have an over state of #525151 also to indicate that they're clickable. I realize that well lose these over states on mobile, but I think that's okay.
- [x] I also believe the footer should lock to the bottom of the screen. It's 115px tall... shouldn't get any taller.
  New from Antony/Galen:
- [x] Footer content should always appear 135 pixels from the bottom, rather than having ton of empty black space follow 
- [x] Footer font is supposed to be condensed, if this isn't possible with the free google fonts, then let's try a smaller font as what appears now is too large.
- [x] Add photo credit to slideshow
- [x] Add descriptive info "title field" that appears at bottom of slideshow
- [x] Add twitter scroll pulling twitter.com/free103point9 (and twitter/wgxc?)
